services:
  web:
    build:
      context: ./generate-random-str
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
